# Ligat HaAl round-by-round ranking changes

- **Regular**: cumulative tables from TM `matches_*_ligat_haal_transfermarkt[_dated].csv`.
- **Split era**: subgroup pools from TM tracking CSVs; carry points halved before mini-leagues. **2009/10 and 2010/11** use **truncation `pts // 2` (documented)**; other seasons use `int(round(pts / 2))`.
- **Playoffs**: TM rounds after `regular_last_round` when present; else Betexplorer `scraped_betexplorer/championship_*.csv` and `relegation_*.csv`.
- **Cell 1 (export)**: with `SEASONS = None`, processes **all** seasons that have `regular_season_tracking_*.csv` and writes full CSVs.
- **Cell 2 (optional)**: prints long text reports for a **small example list** only — not the full league list.
- Output: `notebooks/data/processed/rank_dynamics/`; each block lists rank moves or **No ranking changes in this round**.

In [2]:
from __future__ import annotations
import sys
from pathlib import Path

# Resolve `notebooks/` root whether cwd is `notebooks/` or a parent repo folder
cwd = Path.cwd().resolve()

def resolve_notebooks_root() -> Path:
    for base in [cwd, *cwd.parents]:
        if (base / "league_dynamics" / "rank_tracking.py").is_file():
            return base
        nb = base / "notebooks"
        if (nb / "league_dynamics" / "rank_tracking.py").is_file():
            return nb
    raise FileNotFoundError(
        "Could not find notebooks/league_dynamics/rank_tracking.py "
        "(set kernel cwd to the directory that contains `league_dynamics/` or `notebooks/league_dynamics/`)."
    )

ROOT = resolve_notebooks_root()

if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from league_dynamics import rank_tracking as rt

OUT = ROOT / "data" / "processed" / "rank_dynamics"
OUT.mkdir(parents=True, exist_ok=True)

SEASONS = None  # None = every season that has regular_season_tracking_*.csv; or e.g. ["2015/16"]
changes_df, meta_df = rt.run_all_seasons(SEASONS)

changes_df.to_csv(OUT / "rank_changes_export.csv", index=False, encoding="utf-8-sig")
meta_df.to_csv(OUT / "rank_dynamics_season_meta.csv", index=False, encoding="utf-8-sig")
print("Wrote:", OUT, "| seasons in export:", meta_df.shape[0])

try:
    display(meta_df.head(15))
    display(changes_df.head(40))
except NameError:
    print(meta_df.head())
    print(changes_df.head())

Wrote: C:\Users\nitib\dev-lab\ligat_haal_project\ligat_haal_project\notebooks\data\processed\rank_dynamics | seasons in export: 19

,season,explicit_kizuz,regular_last_round,playoff_source,warnings,notes
0,2006/07,False,33,none,[],Legacy era: no playoff split tracked for this ...
1,2007/08,False,33,none,[],Legacy era: no playoff split tracked for this ...
2,2008/09,False,33,none,[],Legacy era: no playoff split tracked for this ...
3,2009/10,True,30,betexplorer,[],Subgroup tables after the split: ranks are wit...
4,2010/11,True,30,betexplorer,[],Subgroup tables after the split: ranks are wit...
5,2011/12,False,30,betexplorer,[],Subgroup tables after the split: ranks are wit...
6,2012/13,False,26,betexplorer,[],Subgroup tables after the split: ranks are wit...
7,2013/14,False,26,betexplorer,[],Subgroup tables after the split: ranks are wit...
8,2014/15,False,26,betexplorer,[],Subgroup tables after the split: ranks are wit...
9,2015/16,False,26,betexplorer,[],Subgroup tables after the split: ranks are wit...
10,2016/17,False,26,betexplorer,[],Subgroup tables after the split: ranks are wit...
11,2017/18,False,26,betexplorer,[],Subgroup tables after the split: ranks are wit...
12,2018/19,False,26,betexplorer,[],Subgroup tables after the split: ranks are wit...
13,2019/20,False,26,betexplorer,[],Subgroup tables after the split: ranks are wit...
14,2020/21,False,26,betexplorer,[],Subgroup tables after the split: ranks are wit...

,season,stage,segment_label,team,prev_rank,new_rank
0,2006/07,regular,Regular: after round 2 vs after round 1,B. Jerusalem,3,2
1,2006/07,regular,Regular: after round 2 vs after round 1,Bnei Yehuda,5,8
2,2006/07,regular,Regular: after round 2 vs after round 1,FC Ashdod,4,6
3,2006/07,regular,Regular: after round 2 vs after round 1,H. Petah Tikva,12,10
4,2006/07,regular,Regular: after round 2 vs after round 1,Hakoah Amidar,7,5
5,2006/07,regular,Regular: after round 2 vs after round 1,Hapoel Tel Aviv,6,9
6,2006/07,regular,Regular: after round 2 vs after round 1,M. Petah Tikva,8,3
7,2006/07,regular,Regular: after round 2 vs after round 1,M. Tel Aviv,9,11
8,2006/07,regular,Regular: after round 2 vs after round 1,Maccabi Haifa,11,7
9,2006/07,regular,Regular: after round 2 vs after round 1,Maccabi Herzlya,10,12
10,2006/07,regular,Regular: after round 2 vs after round 1,Maccabi Netanya,2,4
11,2006/07,regular,Regular: after round 3 vs after round 2,B. Jerusalem,2,1
12,2006/07,regular,Regular: after round 3 vs after round 2,FC Ashdod,6,3
13,2006/07,regular,Regular: after round 3 vs after round 2,H. Kfar Saba,1,2
14,2006/07,regular,Regular: after round 3 vs after round 2,H. Petah Tikva,10,11
15,2006/07,regular,Regular: after round 3 vs after round 2,Hakoah Amidar,5,9
16,2006/07,regular,Regular: after round 3 vs after round 2,Hapoel Tel Aviv,9,6
17,2006/07,regular,Regular: after round 3 vs after round 2,M. Petah Tikva,3,7
18,2006/07,regular,Regular: after round 3 vs after round 2,M. Tel Aviv,11,10
19,2006/07,regular,Regular: after round 3 vs after round 2,Maccabi Haifa,7,4
20,2006/07,regular,Regular: after round 3 vs after round 2,Maccabi Netanya,4,5
21,2006/07,regular,Regular: after round 4 vs after round 3,Bnei Yehuda,8,9
22,2006/07,regular,Regular: after round 4 vs after round 3,FC Ashdod,3,6
23,2006/07,regular,Regular: after round 4 vs after round 3,H. Kfar Saba,2,3
24,2006/07,regular,Regular: after round 4 vs after round 3,H. Petah Tikva,11,12
25,2006/07,regular,Regular: after round 4 vs after round 3,Hakoah Amidar,9,8
26,2006/07,regular,Regular: after round 4 vs after round 3,Hapoel Tel Aviv,6,7
27,2006/07,regular,Regular: after round 4 vs after round 3,M. Petah Tikva,7,4
28,2006/07,regular,Regular: after round 4 vs after round 3,Maccabi Haifa,4,2
29,2006/07,regular,Regular: after round 4 vs after round 3,Maccabi Herzlya,12,11
30,2006/07,regular,Regular: after round 5 vs after round 4,B. Jerusalem,1,2
31,2006/07,regular,Regular: after round 5 vs after round 4,Bnei Yehuda,9,8
32,2006/07,regular,Regular: after round 5 vs after round 4,FC Ashdod,6,4
33,2006/07,regular,Regular: after round 5 vs after round 4,H. Kfar Saba,3,7
34,2006/07,regular,Regular: after round 5 vs after round 4,Hakoah Amidar,8,9
35,2006/07,regular,Regular: after round 5 vs after round 4,Hapoel Tel Aviv,7,6
36,2006/07,regular,Regular: after round 5 vs after round 4,M. Petah Tikva,4,1
37,2006/07,regular,Regular: after round 5 vs after round 4,Maccabi Haifa,2,5
38,2006/07,regular,Regular: after round 5 vs after round 4,Maccabi Netanya,5,3
39,2006/07,regular,Regular: after round 6 vs after round 5,B. Jerusalem,2,1

In [3]:
# Optional: readable console sample only (three seasons shown as examples — full universe is Cell 1)
SAMPLE_PRINT = ["2009/10", "2010/11", "2015/16"]
for sea in SAMPLE_PRINT:
    notes, blocks, val = rt.analyze_season(sea)
    print(rt.format_season_report(notes, blocks, val))
    print()

Season 2009/10:
  Notes:
    - Points halved before playoff groups: True
    - SPECIAL (2009/10 or 2010/11): חוק הקיזוז — carry points truncated with integer division pts // 2
    - Regular season ended after TM round 30
    - Playoff fixture source where applicable: betexplorer
    - Subgroup tables after the split: ranks are within the championship or relegation cohort only (not comparable to pre-split global rank 1–N).
    - Points from the regular season are halved for playoff carry points; goal difference from the regular phase is carried for tie-breaks within each mini-league.
    - חוק הקיזוז seasons (2009/10, 2010/11): carry points halved with integer truncation (pts // 2).
  [regular] Regular: after round 2 vs after round 1
    B. Jerusalem: rank 9 -> 11
    Bnei Sakhnin: rank 15 -> 14
    FC Ashdod: rank 16 -> 7
    H. Beer Sheva: rank 3 -> 4
    H. Petah Tikva: rank 4 -> 6
    H. Ramat Gan: rank 7 -> 8
    Hapoel Acre: rank 11 -> 12
    Hapoel Raanana: rank 12 -> 15
    M. Ahi Nazareth: rank 13 -> 16
    M. Petah Tikva: rank 8 -> 9
    Maccabi Haifa: rank 6 -> 3
    Maccabi Netanya: rank 14 -> 13
  [regular] Regular: after round 3 vs after round 2
    B. Jerusalem: rank 11 -> 7
    Bnei Sakhnin: rank 14 -> 8
    Bnei Yehuda: rank 1 -> 2
    FC Ashdod: rank 7 -> 5
    H. Beer Sheva: rank 4 -> 9
    H. Petah Tikva: rank 6 -> 10
    H. Ramat Gan: rank 8 -> 12
    Hapoel Acre: rank 12 -> 14
    Hapoel Haifa: rank 5 -> 4
    Hapoel Tel Aviv: rank 10 -> 6
    M. Petah Tikva: rank 9 -> 13
    M. Tel Aviv: rank 2 -> 3
    Maccabi Haifa: rank 3 -> 1
    Maccabi Netanya: rank 13 -> 11
  [regular] Regular: after round 4 vs after round 3
    B. Jerusalem: rank 7 -> 4
    Bnei Sakhnin: rank 8 -> 10
    FC Ashdod: rank 5 -> 6
    H. Beer Sheva: rank 9 -> 11
    H. Petah Tikva: rank 10 -> 13
    H. Ramat Gan: rank 12 -> 9
    Hapoel Acre: rank 14 -> 16
    Hapoel Haifa: rank 4 -> 3
    Hapoel Tel Aviv: rank 6 -> 8
    M. Ahi Nazareth: rank 16 -> 12
    M. Petah Tikva: rank 13 -> 7
    M. Tel Aviv: rank 3 -> 5
    Maccabi Netanya: rank 11 -> 14
  [regular] Regular: after round 5 vs after round 4
    Bnei Sakhnin: rank 10 -> 12
    Bnei Yehuda: rank 2 -> 3
    FC Ashdod: rank 6 -> 7
    H. Beer Sheva: rank 11 -> 8
    Hapoel Acre: rank 16 -> 14
    Hapoel Haifa: rank 3 -> 2
    Hapoel Tel Aviv: rank 8 -> 5
    M. Ahi Nazareth: rank 12 -> 10
    M. Petah Tikva: rank 7 -> 11
    M. Tel Aviv: rank 5 -> 6
    Maccabi Netanya: rank 14 -> 16
  [regular] Regular: after round 6 vs after round 5
    Bnei Sakhnin: rank 12 -> 14
    Bnei Yehuda: rank 3 -> 5
    H. Beer Sheva: rank 8 -> 9
    H. Petah Tikva: rank 13 -> 10
    H. Ramat Gan: rank 9 -> 11
    Hapoel Acre: rank 14 -> 15
    Hapoel Raanana: rank 15 -> 16
    Hapoel Tel Aviv: rank 5 -> 6
    M. Ahi Nazareth: rank 10 -> 8
    M. Petah Tikva: rank 11 -> 13
    M. Tel Aviv: rank 6 -> 3
    Maccabi Netanya: rank 16 -> 12
  [regular] Regular: after round 7 vs after round 6
    B. Jerusalem: rank 4 -> 6
    Bnei Yehuda: rank 5 -> 3
    H. Ramat Gan: rank 11 -> 12
    Hapoel Haifa: rank 2 -> 5
    Hapoel Tel Aviv: rank 6 -> 4
    M. Tel Aviv: rank 3 -> 2
    Maccabi Netanya: rank 12 -> 11
  [regular] Regular: after round 8 vs after round 7
    B. Jerusalem: rank 6 -> 4
    FC Ashdod: rank 7 -> 8
    H. Beer Sheva: rank 9 -> 7
    H. Petah Tikva: rank 10 -> 12
    H. Ramat Gan: rank 12 -> 9
    Hapoel Acre: rank 15 -> 16
    Hapoel Haifa: rank 5 -> 6
    Hapoel Raanana: rank 16 -> 15
    Hapoel Tel Aviv: rank 4 -> 2
    M. Ahi Nazareth: rank 8 -> 11
    M. Petah Tikva: rank 13 -> 10
    M. Tel Aviv: rank 2 -> 5
    Maccabi Netanya: rank 11 -> 13
  [regular] Regular: after round 9 vs after round 8
    B. Jerusalem: rank 4 -> 5
    Bnei Sakhnin: rank 14 -> 15
    FC Ashdod: rank 8 -> 10
    H. Beer Sheva: rank 7 -> 6
    H. Ramat Gan: rank 9 -> 8
    Hapoel Acre: rank 16 -> 14
    Hapoel Haifa: rank 6 -> 7
    Hapoel Raanana: rank 15 -> 16
    M. Ahi Nazareth: rank 11 -> 13
    M. Petah Tikva: rank 10 -> 9
    M. Tel Aviv: rank 5 -> 4
    Maccabi Netanya: rank 13 -> 11
  [regular] Regular: after round 10 vs after round 9
    Bnei Sakhnin: rank 15 -> 13
    FC Ashdod: rank 10 -> 7
    H. Petah Tikva: rank 12 -> 15
    H. Ramat Gan: rank 8 -> 10
    Hapoel Acre: rank 14 -> 11
    Hapoel Haifa: rank 7 -> 8
    Hapoel Raanana: rank 16 -> 14
    M. Ahi Nazareth: rank 13 -> 16
    Maccabi Netanya: rank 11 -> 12
  [regular] Regular: after round 11 vs after round 10
    B. Jerusalem: rank 5 -> 6
    Bnei Yehuda: rank 3 -> 4
    FC Ashdod: rank 7 -> 5
    H. Beer Sheva: rank 6 -> 7
    H. Ramat Gan: rank 10 -> 11
    Hapoel Acre: rank 11 -> 12
    M. Petah Tikva: rank 9 -> 10
    M. Tel Aviv: rank 4 -> 3
    Maccabi Netanya: rank 12 -> 9
  [regular] Regular: after round 12 vs after round 11
    Bnei Yehuda: rank 4 -> 3
    H. Ramat Gan: rank 11 -> 10
    Hapoel Acre: rank 12 -> 11
    Hapoel Haifa: rank 8 -> 9
    M. Petah Tikva: rank 10 -> 12
    M. Tel Aviv: rank 3 -> 4
    Maccabi Netanya: rank 9 -> 8
  [regular] Regular: after round 13 vs after round 12
    B. Jerusalem: rank 6 -> 5
    Bnei Sakhnin: rank 13 -> 14
    FC Ashdod: rank 5 -> 7
    H. Beer Sheva: rank 7 -> 6
    Hapoel Raanana: rank 14 -> 13
  [regular] Regular: after round 14 vs after round 13
    Bnei Sakhnin: rank 14 -> 13
    Bnei Yehuda: rank 3 -> 4
    H. Beer Sheva: rank 6 -> 9
    H. Petah Tikva: rank 15 -> 16
    H. Ramat Gan: rank 10 -> 11
    Hapoel Acre: rank 11 -> 10
    Hapoel Haifa: rank 9 -> 8
    Hapoel Raanana: rank 13 -> 14
    M. Ahi Nazareth: rank 16 -> 15
    M. Tel Aviv: rank 4 -> 3
    Maccabi Netanya: rank 8 -> 6
  [regular] Regular: after round 15 vs after round 14
    FC Ashdod: rank 7 -> 8
    H. Beer Sheva: rank 9 -> 6
    Hapoel Haifa: rank 8 -> 9
    Hapoel Raanana: rank 14 -> 12
    M. Petah Tikva: rank 12 -> 14
    Maccabi Netanya: rank 6 -> 7
  [regular] Regular: after round 16 vs after round 15
    Bnei Sakhnin: rank 13 -> 15
    FC Ashdod: rank 8 -> 6
    H. Beer Sheva: rank 6 -> 7
    H. Petah Tikva: rank 16 -> 14
    Hapoel Raanana: rank 12 -> 13
    M. Ahi Nazareth: rank 15 -> 16
    M. Petah Tikva: rank 14 -> 12
    Maccabi Netanya: rank 7 -> 8
  [regular] Regular: after round 17 vs after round 16
    H. Ramat Gan: rank 11 -> 12
    M. Petah Tikva: rank 12 -> 11
  [regular] Regular: after round 18 vs after round 17
    B. Jerusalem: rank 5 -> 6
    FC Ashdod: rank 6 -> 5
    H. Beer Sheva: rank 7 -> 8
    H. Petah Tikva: rank 14 -> 13
    H. Ramat Gan: rank 12 -> 14
    Hapoel Acre: rank 10 -> 11
    Hapoel Raanana: rank 13 -> 12
    M. Petah Tikva: rank 11 -> 10
    Maccabi Netanya: rank 8 -> 7
  [regular] Regular: after round 19 vs after round 18
    Bnei Sakhnin: rank 15 -> 12
    H. Petah Tikva: rank 13 -> 15
    H. Ramat Gan: rank 14 -> 11
    Hapoel Acre: rank 11 -> 13
    Hapoel Raanana: rank 12 -> 14
  [regular] Regular: after round 20 vs after round 19
    Bnei Sakhnin: rank 12 -> 11
    H. Petah Tikva: rank 15 -> 14
    H. Ramat Gan: rank 11 -> 12
    Hapoel Acre: rank 13 -> 16
    Hapoel Raanana: rank 14 -> 13
    M. Ahi Nazareth: rank 16 -> 15
  [regular] Regular: after round 21 vs after round 20
    B. Jerusalem: rank 6 -> 5
    Bnei Sakhnin: rank 11 -> 9
    FC Ashdod: rank 5 -> 6
    H. Petah Tikva: rank 14 -> 13
    Hapoel Haifa: rank 9 -> 10
    Hapoel Raanana: rank 13 -> 14
    M. Petah Tikva: rank 10 -> 11
  [regular] Regular: after round 22 vs after round 21
    B. Jerusalem: rank 5 -> 6
    FC Ashdod: rank 6 -> 5
    H. Beer Sheva: rank 8 -> 7
    Hapoel Acre: rank 16 -> 14
    Hapoel Haifa: rank 10 -> 11
    Hapoel Raanana: rank 14 -> 15
    M. Ahi Nazareth: rank 15 -> 16
    M. Petah Tikva: rank 11 -> 10
    Maccabi Netanya: rank 7 -> 8
  [regular] Regular: after round 23 vs after round 22
    B. Jerusalem: rank 6 -> 7
    H. Beer Sheva: rank 7 -> 8
    H. Petah Tikva: rank 13 -> 12
    H. Ramat Gan: rank 12 -> 13
    Maccabi Netanya: rank 8 -> 6
  [regular] Regular: after round 24 vs after round 23
    B. Jerusalem: rank 7 -> 6
    Bnei Sakhnin: rank 9 -> 10
    Hapoel Raanana: rank 15 -> 16
    M. Ahi Nazareth: rank 16 -> 15
    M. Petah Tikva: rank 10 -> 9
    Maccabi Netanya: rank 6 -> 7
  [regular] Regular: after round 25 vs after round 24
    Bnei Sakhnin: rank 10 -> 11
    H. Petah Tikva: rank 12 -> 13
    H. Ramat Gan: rank 13 -> 12
    Hapoel Haifa: rank 11 -> 10
    M. Petah Tikva: rank 9 -> 7
    Maccabi Netanya: rank 7 -> 9
  [regular] Regular: after round 26 vs after round 25
    B. Jerusalem: rank 6 -> 5
    FC Ashdod: rank 5 -> 6
    H. Beer Sheva: rank 8 -> 7
    M. Petah Tikva: rank 7 -> 9
    Maccabi Netanya: rank 9 -> 8
  [regular] Regular: after round 27 vs after round 26
    Bnei Sakhnin: rank 11 -> 10
    H. Beer Sheva: rank 7 -> 8
    Hapoel Haifa: rank 10 -> 11
    Maccabi Netanya: rank 8 -> 7
  [regular] Regular: after round 28 vs after round 27
    B. Jerusalem: rank 5 -> 4
    Bnei Sakhnin: rank 10 -> 9
    Bnei Yehuda: rank 4 -> 5
    H. Beer Sheva: rank 8 -> 7
    H. Ramat Gan: rank 12 -> 11
    Hapoel Haifa: rank 11 -> 12
    M. Petah Tikva: rank 9 -> 10
    Maccabi Netanya: rank 7 -> 8
  [regular] Regular: after round 29 vs after round 28
    Bnei Sakhnin: rank 9 -> 7
    H. Beer Sheva: rank 7 -> 8
    Maccabi Netanya: rank 8 -> 9
  [regular] Regular: after round 30 vs after round 29
    No ranking changes in this round
  [championship_playoff] championship playoff: after mini-league round 1 vs halved-carry table (before any playoff match)
    Hapoel Tel Aviv: rank 2 -> 1
    Maccabi Haifa: rank 1 -> 2
  [championship_playoff] championship playoff: after mini-league round 2 vs after mini-league round 1
    No ranking changes in this round
  [championship_playoff] championship playoff: after mini-league round 3 vs after mini-league round 2
    No ranking changes in this round
  [championship_playoff] championship playoff: after mini-league round 4 vs after mini-league round 3
    No ranking changes in this round
  [championship_playoff] championship playoff: after mini-league round 5 vs after mini-league round 4
    No ranking changes in this round
  [relegation_playoff] relegation playoff: after mini-league round 1 vs halved-carry table (before any playoff match)
    No ranking changes in this round
  [relegation_playoff] relegation playoff: after mini-league round 2 vs after mini-league round 1
    No ranking changes in this round
  [relegation_playoff] relegation playoff: after mini-league round 3 vs after mini-league round 2
    No ranking changes in this round
  [relegation_playoff] relegation playoff: after mini-league round 4 vs after mini-league round 3
    No ranking changes in this round
  [relegation_playoff] relegation playoff: after mini-league round 5 vs after mini-league round 4
    No ranking changes in this round

Season 2010/11:
  Notes:
    - Points halved before playoff groups: True
    - SPECIAL (2009/10 or 2010/11): חוק הקיזוז — carry points truncated with integer division pts // 2
    - Regular season ended after TM round 30
    - Playoff fixture source where applicable: betexplorer
    - Subgroup tables after the split: ranks are within the championship or relegation cohort only (not comparable to pre-split global rank 1–N).
    - Points from the regular season are halved for playoff carry points; goal difference from the regular phase is carried for tie-breaks within each mini-league.
    - חוק הקיזוז seasons (2009/10, 2010/11): carry points halved with integer truncation (pts // 2).
  [regular] Regular: after round 2 vs after round 1
    Bnei Sakhnin: rank 15 -> 14
    Bnei Yehuda: rank 8 -> 6
    FC Ashdod: rank 4 -> 5
    H. Ashkelon: rank 2 -> 10
    H. Beer Sheva: rank 5 -> 8
    H. Petah Tikva: rank 14 -> 13
    H. Ramat Gan: rank 9 -> 12
    Hapoel Acre: rank 10 -> 11
    Hapoel Haifa: rank 6 -> 1
    Hapoel Tel Aviv: rank 11 -> 7
    Kiryat Shmona: rank 3 -> 4
    M. Petah Tikva: rank 12 -> 15
    M. Tel Aviv: rank 13 -> 9
    Maccabi Haifa: rank 7 -> 2
    Maccabi Netanya: rank 1 -> 3
  [regular] Regular: after round 3 vs after round 2
    Bnei Sakhnin: rank 14 -> 15
    Bnei Yehuda: rank 6 -> 9
    FC Ashdod: rank 5 -> 8
    H. Beer Sheva: rank 8 -> 7
    H. Petah Tikva: rank 13 -> 14
    H. Ramat Gan: rank 12 -> 13
    Hapoel Acre: rank 11 -> 12
    Hapoel Tel Aviv: rank 7 -> 6
    Kiryat Shmona: rank 4 -> 3
    M. Petah Tikva: rank 15 -> 11
    M. Tel Aviv: rank 9 -> 5
    Maccabi Haifa: rank 2 -> 4
    Maccabi Netanya: rank 3 -> 2
  [regular] Regular: after round 4 vs after round 3
    B. Jerusalem: rank 16 -> 13
    Bnei Sakhnin: rank 15 -> 16
    Bnei Yehuda: rank 9 -> 11
    FC Ashdod: rank 8 -> 10
    H. Ashkelon: rank 10 -> 6
    H. Beer Sheva: rank 7 -> 12
    H. Petah Tikva: rank 14 -> 15
    H. Ramat Gan: rank 13 -> 8
    Hapoel Acre: rank 12 -> 14
    Hapoel Haifa: rank 1 -> 4
    Hapoel Tel Aviv: rank 6 -> 9
    Kiryat Shmona: rank 3 -> 1
    M. Petah Tikva: rank 11 -> 7
    M. Tel Aviv: rank 5 -> 3
    Maccabi Haifa: rank 4 -> 2
    Maccabi Netanya: rank 2 -> 5
  [regular] Regular: after round 5 vs after round 4
    B. Jerusalem: rank 13 -> 14
    Bnei Yehuda: rank 11 -> 13
    FC Ashdod: rank 10 -> 12
    H. Beer Sheva: rank 12 -> 9
    H. Ramat Gan: rank 8 -> 11
    Hapoel Acre: rank 14 -> 10
    Hapoel Tel Aviv: rank 9 -> 7
    M. Petah Tikva: rank 7 -> 8
    M. Tel Aviv: rank 3 -> 2
    Maccabi Haifa: rank 2 -> 3
  [regular] Regular: after round 6 vs after round 5
    Bnei Yehuda: rank 13 -> 9
    H. Ashkelon: rank 6 -> 8
    H. Beer Sheva: rank 9 -> 10
    H. Ramat Gan: rank 11 -> 13
    Hapoel Acre: rank 10 -> 11
    Hapoel Haifa: rank 4 -> 7
    Hapoel Tel Aviv: rank 7 -> 5
    M. Petah Tikva: rank 8 -> 6
    M. Tel Aviv: rank 2 -> 3
    Maccabi Haifa: rank 3 -> 2
    Maccabi Netanya: rank 5 -> 4
  [regular] Regular: after round 7 vs after round 6
    B. Jerusalem: rank 14 -> 13
    Bnei Yehuda: rank 9 -> 11
    H. Ashkelon: rank 8 -> 7
    H. Ramat Gan: rank 13 -> 14
    Hapoel Acre: rank 11 -> 9
    Hapoel Haifa: rank 7 -> 8
    Hapoel Tel Aviv: rank 5 -> 4
    M. Tel Aviv: rank 3 -> 2
    Maccabi Haifa: rank 2 -> 3
    Maccabi Netanya: rank 4 -> 5
  [regular] Regular: after round 8 vs after round 7
    Bnei Yehuda: rank 11 -> 9
    FC Ashdod: rank 12 -> 10
    H. Ashkelon: rank 7 -> 11
    H. Beer Sheva: rank 10 -> 12
    Hapoel Acre: rank 9 -> 7
    Kiryat Shmona: rank 1 -> 2
    M. Tel Aviv: rank 2 -> 3
    Maccabi Haifa: rank 3 -> 1
  [regular] Regular: after round 9 vs after round 8
    B. Jerusalem: rank 13 -> 14
    Bnei Yehuda: rank 9 -> 10
    FC Ashdod: rank 10 -> 8
    H. Ashkelon: rank 11 -> 12
    H. Beer Sheva: rank 12 -> 11
    H. Petah Tikva: rank 15 -> 13
    H. Ramat Gan: rank 14 -> 15
    Hapoel Acre: rank 7 -> 5
    Hapoel Haifa: rank 8 -> 7
    Hapoel Tel Aviv: rank 4 -> 2
    Kiryat Shmona: rank 2 -> 3
    M. Petah Tikva: rank 6 -> 9
    M. Tel Aviv: rank 3 -> 1
    Maccabi Haifa: rank 1 -> 4
    Maccabi Netanya: rank 5 -> 6
  [regular] Regular: after round 10 vs after round 9
    B. Jerusalem: rank 14 -> 13
    FC Ashdod: rank 8 -> 9
    H. Petah Tikva: rank 13 -> 14
    Hapoel Haifa: rank 7 -> 8
    Hapoel Tel Aviv: rank 2 -> 3
    Kiryat Shmona: rank 3 -> 1
    M. Petah Tikva: rank 9 -> 6
    M. Tel Aviv: rank 1 -> 4
    Maccabi Haifa: rank 4 -> 2
    Maccabi Netanya: rank 6 -> 7
  [regular] Regular: after round 11 vs after round 10
    Bnei Yehuda: rank 10 -> 11
    FC Ashdod: rank 9 -> 10
    H. Beer Sheva: rank 11 -> 9
    Hapoel Acre: rank 5 -> 4
    Hapoel Tel Aviv: rank 3 -> 2
    M. Tel Aviv: rank 4 -> 5
    Maccabi Haifa: rank 2 -> 3
  [regular] Regular: after round 12 vs after round 11
    B. Jerusalem: rank 13 -> 12
    Bnei Sakhnin: rank 16 -> 15
    Bnei Yehuda: rank 11 -> 9
    FC Ashdod: rank 10 -> 8
    H. Ashkelon: rank 12 -> 13
    H. Beer Sheva: rank 9 -> 6
    H. Ramat Gan: rank 15 -> 16
    Hapoel Acre: rank 4 -> 5
    Hapoel Haifa: rank 8 -> 11
    Hapoel Tel Aviv: rank 2 -> 3
    M. Petah Tikva: rank 6 -> 7
    M. Tel Aviv: rank 5 -> 4
    Maccabi Haifa: rank 3 -> 2
    Maccabi Netanya: rank 7 -> 10
  [regular] Regular: after round 13 vs after round 12
    Bnei Yehuda: rank 9 -> 10
    FC Ashdod: rank 8 -> 9
    Hapoel Acre: rank 5 -> 7
    Hapoel Haifa: rank 11 -> 8
    Hapoel Tel Aviv: rank 3 -> 2
    Kiryat Shmona: rank 1 -> 3
    M. Petah Tikva: rank 7 -> 5
    Maccabi Haifa: rank 2 -> 1
    Maccabi Netanya: rank 10 -> 11
  [regular] Regular: after round 14 vs after round 13
    Bnei Yehuda: rank 10 -> 11
    FC Ashdod: rank 9 -> 10
    H. Beer Sheva: rank 6 -> 8
    Hapoel Acre: rank 7 -> 5
    Hapoel Haifa: rank 8 -> 7
    M. Petah Tikva: rank 5 -> 6
    Maccabi Netanya: rank 11 -> 9
  [regular] Regular: after round 15 vs after round 14
    B. Jerusalem: rank 12 -> 11
    Bnei Yehuda: rank 11 -> 12
    FC Ashdod: rank 10 -> 8
    H. Ashkelon: rank 13 -> 14
    H. Beer Sheva: rank 8 -> 9
    H. Petah Tikva: rank 14 -> 13
    Kiryat Shmona: rank 3 -> 4
    M. Tel Aviv: rank 4 -> 3
    Maccabi Netanya: rank 9 -> 10
  [regular] Regular: after round 16 vs after round 15
    FC Ashdod: rank 8 -> 7
    H. Ashkelon: rank 14 -> 13
    H. Beer Sheva: rank 9 -> 8
    H. Petah Tikva: rank 13 -> 14
    Hapoel Acre: rank 5 -> 6
    Hapoel Haifa: rank 7 -> 9
    M. Petah Tikva: rank 6 -> 5
  [regular] Regular: after round 17 vs after round 16
    FC Ashdod: rank 7 -> 8
    H. Beer Sheva: rank 8 -> 9
    Hapoel Acre: rank 6 -> 5
    Hapoel Haifa: rank 9 -> 7
    M. Petah Tikva: rank 5 -> 6
  [regular] Regular: after round 18 vs after round 17
    B. Jerusalem: rank 11 -> 12
    Bnei Yehuda: rank 12 -> 11
    FC Ashdod: rank 8 -> 7
    H. Beer Sheva: rank 9 -> 8
    Hapoel Acre: rank 5 -> 6
    Hapoel Haifa: rank 7 -> 9
    Hapoel Tel Aviv: rank 2 -> 1
    M. Petah Tikva: rank 6 -> 5
    Maccabi Haifa: rank 1 -> 2
  [regular] Regular: after round 19 vs after round 18
    B. Jerusalem: rank 12 -> 11
    Bnei Yehuda: rank 11 -> 12
    H. Beer Sheva: rank 8 -> 9
    Hapoel Acre: rank 6 -> 5
    Hapoel Haifa: rank 9 -> 8
    Hapoel Tel Aviv: rank 1 -> 2
    M. Petah Tikva: rank 5 -> 6
    Maccabi Haifa: rank 2 -> 1
  [regular] Regular: after round 20 vs after round 19
    B. Jerusalem: rank 11 -> 12
    Bnei Sakhnin: rank 15 -> 14
    Bnei Yehuda: rank 12 -> 10
    H. Petah Tikva: rank 14 -> 15
    Hapoel Acre: rank 5 -> 6
    Hapoel Tel Aviv: rank 2 -> 1
    M. Petah Tikva: rank 6 -> 5
    Maccabi Haifa: rank 1 -> 2
    Maccabi Netanya: rank 10 -> 11
  [regular] Regular: after round 21 vs after round 20
    Bnei Sakhnin: rank 14 -> 15
    Bnei Yehuda: rank 10 -> 11
    FC Ashdod: rank 7 -> 10
    H. Beer Sheva: rank 9 -> 8
    H. Petah Tikva: rank 15 -> 14
    Hapoel Acre: rank 6 -> 5
    Hapoel Haifa: rank 8 -> 7
    Hapoel Tel Aviv: rank 1 -> 2
    M. Petah Tikva: rank 5 -> 6
    Maccabi Haifa: rank 2 -> 1
    Maccabi Netanya: rank 11 -> 9
  [regular] Regular: after round 22 vs after round 21
    Bnei Yehuda: rank 11 -> 10
    FC Ashdod: rank 10 -> 11
    H. Ashkelon: rank 13 -> 14
    H. Beer Sheva: rank 8 -> 9
    H. Petah Tikva: rank 14 -> 13
    Hapoel Haifa: rank 7 -> 8
    Maccabi Netanya: rank 9 -> 7
  [regular] Regular: after round 23 vs after round 22
    Bnei Yehuda: rank 10 -> 9
    H. Beer Sheva: rank 9 -> 10
    Hapoel Acre: rank 5 -> 6
    M. Petah Tikva: rank 6 -> 5
  [regular] Regular: after round 24 vs after round 23
    Bnei Yehuda: rank 9 -> 7
    Hapoel Haifa: rank 8 -> 9
    Hapoel Tel Aviv: rank 2 -> 1
    Maccabi Haifa: rank 1 -> 2
    Maccabi Netanya: rank 7 -> 8
  [regular] Regular: after round 25 vs after round 24
    Bnei Sakhnin: rank 15 -> 14
    Bnei Yehuda: rank 7 -> 6
    H. Ashkelon: rank 14 -> 15
    Hapoel Acre: rank 6 -> 8
    Hapoel Haifa: rank 9 -> 7
    Hapoel Tel Aviv: rank 1 -> 2
    Maccabi Haifa: rank 2 -> 1
    Maccabi Netanya: rank 8 -> 9
  [regular] Regular: after round 26 vs after round 25
    B. Jerusalem: rank 12 -> 11
    FC Ashdod: rank 11 -> 12
    Hapoel Acre: rank 8 -> 7